name: Go

on:
  push:
    branches: [ master, 'feature/**' ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    # Service containers to run with `build`
    services:
      # Label used to access the service container
      rabbitmq:
        # Docker Hub image
        image: rabbitmq:3-management

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies for Elastic Uploader
      run: |
        cd ./elasticuploader
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build Elastic Uploader
      run: |
        cd ./elasticuploader
        go build -o elasticuploader -v ./cmd

    - name: Test Elastic Uploader
      run: |
        cd ./elasticuploader
        go test -v ./cmd

    - name: Get dependencies for Parser
      run: |
        cd ./parser
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build Parser
      run: |
        cd ./parser
        go build -o parser -v ./cmd

    - name: Test Parser
      run: |
        cd ./parser/tests
        go test -v ./...
